Repository KhronosGroup/Vulkan-Samples, pull requests merged in 2024-11, with the labels that each got.

#1205 Add missing request of Vulkan1.2 feature scalarBlockLayout
  samples/extensions/ray_tracing_reflection/ray_tracing_reflection.cpp
Labels: bugfix

#1177 iOS / macOS build fixes, iOS Simulator for x86_64 hosts, VS and Xcode build/run configs
  .github/workflows/build.yml
  app/CMakeLists.txt
  app/ios/Info.plist
  bldsys/cmake/global_options.cmake
  bldsys/cmake/module/FindVulkan.cmake
  docs/build.adoc
  framework/vulkan_sample.h
  samples/api/hello_triangle/hello_triangle.cpp
  samples/api/hpp_hello_triangle/hpp_hello_triangle.cpp
  third_party/CMakeLists.txt
Labels: build, Mac

#1212 Add compile option -fno-strict-aliasing for all compilers but MSVC.
  CMakeLists.txt
Labels: bugfix

#1221 Remove xref from external links, fix link to tracy pdf
  docs/build.adoc
  samples/extensions/README.adoc
  samples/extensions/dynamic_rendering_local_read/README.adoc
Labels: documentation

#1223 Remove jeykll github pages deployment
  .github/workflows/jekyll-gh-pages.yml
Labels: build

#1203 Extend supported classes in vkb::scene_graph::HPPScene::get_components and vkb::scene_graph::HPPScene::has_components
  framework/scene_graph/hpp_scene.h
Labels: framework

#1220 Transcoded version of extension sample push_descriptors based on Vulkan-Hpp
  antora/modules/ROOT/nav.adoc
  samples/CMakeLists.txt
  samples/extensions/README.adoc
  samples/extensions/hpp_push_descriptors/CMakeLists.txt
  samples/extensions/hpp_push_descriptors/README.adoc
  samples/extensions/hpp_push_descriptors/hpp_push_descriptors.cpp
  samples/extensions/hpp_push_descriptors/hpp_push_descriptors.h
Labels: sample

#1229 Readme update
  README.adoc
  antora/CMakeLists.txt
  third_party/README.adoc
Labels: documentation
