Repository KhronosGroup/Vulkan-Samples, pull requests merged in 2024-08, with the labels that each got.

#1117 Fix actions/upload-pages-artifact version
  .github/workflows/jekyll-gh-pages.yml
Labels: urgent

#1119 Fix profiles sample for Apple platforms
  samples/tooling/profiles/profiles.cpp
Labels: Mac

#1120 Fixes to iOS render loop and HUD overlay.
  .gitignore
  app/ios/Storyboard.storyboard
  framework/platform/ios/ios_window.mm
  framework/platform/platform.cpp
  framework/platform/platform.h
Labels: Mac

#1143 Fix offset of BufferAllocation with C-bindings path (again)
  framework/buffer_pool.h
Labels: bugfix
