Repository KhronosGroup/Vulkan-Samples, pull requests merged in 2024-03, with the labels that each got.

#960 Adjust hpp OIT sample position in documentation navgiation
  antora/modules/ROOT/nav.adoc
Labels: documentation

#968 Make command line help easier to understand
  framework/platform/platform.cpp
  framework/platform/platform.h
Labels: framework

#924 Fix validation errors about using unsupported linear filtering
  framework/api_vulkan_sample.cpp
  framework/common/hpp_vk_common.h
  framework/common/vk_common.cpp
  framework/common/vk_common.h
  framework/gltf_loader.cpp
  framework/gltf_loader.h
  framework/gui.cpp
  framework/hpp_api_vulkan_sample.cpp
  framework/hpp_api_vulkan_sample.h
  framework/hpp_gui.cpp
  framework/rendering/postprocessing_computepass.cpp
  framework/rendering/postprocessing_computepass.h
  framework/rendering/postprocessing_renderpass.cpp
  framework/rendering/postprocessing_renderpass.h
  samples/api/hdr/hdr.cpp
  samples/api/hpp_hdr/hpp_hdr.cpp
  samples/api/hpp_separate_image_sampler/hpp_separate_image_sampler.cpp
  samples/api/hpp_texture_loading/hpp_texture_loading.cpp
  samples/api/hpp_texture_mipmap_generation/hpp_texture_mipmap_generation.cpp
  samples/api/hpp_timestamp_queries/hpp_timestamp_queries.cpp
  samples/api/terrain_tessellation/terrain_tessellation.cpp
  samples/api/texture_loading/texture_loading.cpp
  samples/api/texture_mipmap_generation/texture_mipmap_generation.cpp
  samples/api/timestamp_queries/timestamp_queries.cpp
  samples/extensions/descriptor_indexing/descriptor_indexing.cpp
  samples/extensions/descriptor_indexing/descriptor_indexing.h
  samples/extensions/open_cl_interop/open_cl_interop.cpp
  samples/extensions/open_cl_interop_arm/open_cl_interop_arm.cpp
  samples/extensions/open_gl_interop/open_gl_interop.cpp
  samples/extensions/shader_object/shader_object.cpp
  samples/extensions/sparse_image/sparse_image.cpp
  samples/general/mobile_nerf/mobile_nerf.cpp
  samples/performance/16bit_arithmetic/16bit_arithmetic.cpp
  samples/performance/async_compute/async_compute.cpp
  samples/performance/multi_draw_indirect/multi_draw_indirect.cpp
  samples/performance/multi_draw_indirect/multi_draw_indirect.h
  samples/performance/multithreading_render_passes/multithreading_render_passes.cpp
  samples/performance/texture_compression_basisu/texture_compression_basisu.cpp
Labels: validation

#990 Add offline compilation for HLSL shaders with usage of DXC
  CMakeLists.txt
  bldsys/cmake/sample_helper.cmake
Labels: hlsl

#945 Add new sample for shader debugprintf
  antora/modules/ROOT/nav.adoc
  framework/core/instance.cpp
  framework/core/instance.h
  framework/vulkan_sample.h
  samples/CMakeLists.txt
  samples/extensions/README.adoc
  samples/extensions/shader_debugprintf/CMakeLists.txt
  samples/extensions/shader_debugprintf/README.adoc
  samples/extensions/shader_debugprintf/images/renderdoc_shader_messages.png
  samples/extensions/shader_debugprintf/images/sample.png
  samples/extensions/shader_debugprintf/shader_debugprintf.cpp
  samples/extensions/shader_debugprintf/shader_debugprintf.h
  shaders/shader_debugprintf/scene.frag
  shaders/shader_debugprintf/scene.vert
Labels: sample
