Repository KhronosGroup/Vulkan-Samples, pull requests merged in 2024-02, with the labels that each got.

#907 Clean up some top level projects
  bldsys/cmake/component_helper.cmake
  third_party/CMakeLists.txt
Labels: build

#925 Fix validation errors in *timestamp_queries samples
  framework/common/hpp_vk_common.h
  framework/common/vk_common.cpp
  framework/common/vk_common.h
  samples/api/hdr/hdr.cpp
  samples/api/hpp_hdr/hpp_hdr.cpp
  samples/api/hpp_timestamp_queries/hpp_timestamp_queries.cpp
  samples/api/timestamp_queries/timestamp_queries.cpp
  samples/extensions/calibrated_timestamps/calibrated_timestamps.cpp
Labels: validation

#929 Fix validation error in graphics_pipeline_library
  samples/extensions/graphics_pipeline_library/graphics_pipeline_library.cpp
Labels: validation

#928 Fix validation errors in color_write_enable
  samples/extensions/color_write_enable/color_write_enable.cpp
Labels: validation

#911 Update and fix descriptor buffer tutorial
  samples/extensions/descriptor_buffer_basic/README.adoc
Labels: documentation

#933 Update validation layer
  bldsys/cmake/template/gradle/app.build.gradle.in
  bldsys/cmake/template/gradle/download_vvl.gradle
Labels: validation

#927 Fix validation errors in timeline_semaphores sample
  samples/extensions/timeline_semaphore/timeline_semaphore.cpp
Labels: validation

#733 Add new plugin: real time shader selection
  .copyrightignore
  app/plugins/real_time_shader_selection/real_time_shader_selection.cpp
  app/plugins/real_time_shader_selection/real_time_shader_selection.h
  framework/CMakeLists.txt
  framework/api_vulkan_sample.cpp
  framework/api_vulkan_sample.h
  framework/common/hpp_vk_common.h
  framework/common/vk_common.cpp
  framework/common/vk_common.h
  framework/drawer.cpp
  framework/drawer.h
  framework/gui.cpp
  framework/gui.h
  framework/hpp_api_vulkan_sample.cpp
  framework/hpp_api_vulkan_sample.h
  framework/hpp_gui.cpp
  framework/hpp_gui.h
  framework/hpp_vulkan_sample.cpp
  framework/hpp_vulkan_sample.h
  framework/platform/application.cpp
  framework/platform/application.h
  framework/platform/platform.cpp
  framework/platform/platform.h
  framework/platform/plugins/plugin.h
  framework/platform/plugins/plugin_base.h
  framework/vulkan_sample.cpp
  framework/vulkan_sample.h
  samples/api/dynamic_uniform_buffers/dynamic_uniform_buffers.cpp
  samples/api/hpp_hdr/hpp_hdr.cpp
  samples/api/hpp_hdr/hpp_hdr.h
  samples/api/hpp_instancing/hpp_instancing.cpp
  samples/api/hpp_instancing/hpp_instancing.h
  samples/api/hpp_oit_linked_lists/hpp_oit_linked_lists.cpp
  samples/api/hpp_oit_linked_lists/hpp_oit_linked_lists.h
  samples/api/hpp_separate_image_sampler/hpp_separate_image_sampler.cpp
  samples/api/hpp_separate_image_sampler/hpp_separate_image_sampler.h
  samples/api/hpp_terrain_tessellation/hpp_terrain_tessellation.cpp
  samples/api/hpp_terrain_tessellation/hpp_terrain_tessellation.h
  samples/api/hpp_texture_loading/hpp_texture_loading.cpp
  samples/api/hpp_texture_loading/hpp_texture_loading.h
  samples/api/hpp_texture_mipmap_generation/hpp_texture_mipmap_generation.cpp
  samples/api/hpp_texture_mipmap_generation/hpp_texture_mipmap_generation.h
  samples/api/hpp_timestamp_queries/hpp_timestamp_queries.cpp
  samples/api/hpp_timestamp_queries/hpp_timestamp_queries.h
Labels: hlsl
